services:
  your-lab:
    image: your-lab
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=dev-db