services:
  your-lab:
    image: your-lab
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      dbHost: postgres
      dbPort: 5432
      dbName: your-labs-db
      dbUser: user
      dbPassword: password


  postgres:
    image: 'postgres:16'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your-labs-db


